<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>CadQC</AssemblyName>
    <RootNamespace>CadQC.Cli</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CadQC.Core\CadQC.Core.csproj" />
  </ItemGroup>
</Project>
